apiVersion: apps/v1
kind: Deployment
metadata:
  name:  destination-v2
  labels:
    run:  destination
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      run:  destination
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run:  destination
        version: v2
    spec:
      containers:
      - image:  beetravels/destination-v2:node-471ff48530e5311413108c58cbfd7bc7016f2269
        imagePullPolicy: Always
        name:  destination
        env:
          - name: PORT
            value: "9001"
          - name: HOST_IP
            value: destination
          - name: SCHEME
            value: http
          - name: DESTINATION_DATABASE
            value: postgres
          - name: DESTINATION_MONGO_CONNECTION_URL
            value: mongodb://admin:admin@mongo:27017
          - name: DESTINATION_COUCH_CLOUDANT_CONNECTION_URL
            value: http://admin:admin@couch:5984
          - name: DESTINATION_PG_HOST
            value: bee-travels-db-postgresql
          - name: DESTINATION_PG_USER
            value: postgres
          - name: DESTINATION_PG_PASSWORD
            value: Oyg9YxwKmm
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      
