apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hotel-v1
  labels:
    run:  hotel
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run:  hotel
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run:  hotel
        version: v1
    spec:
      containers:
      - image:  beetravels/hotel-v1:node-471ff48530e5311413108c58cbfd7bc7016f2269
        imagePullPolicy: Always
        name:  hotel
        env:
          - name: PORT
            value: "9101"
          - name: HOST_IP
            value: hotel
          - name: SCHEME
            value: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      
