apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bee-travels-ingress-demo
spec:
  tls:
    - hosts: 
        - bee-travels-summer-proj-442dbba0442be6c8c50f31ed96b00601-0000.us-east.containers.appdomain.cloud
      secretName: bee-travels-summer-proj-442dbba0442be6c8c50f31ed96b00601-0000
  rules:
    - host: bee-travels-summer-proj-442dbba0442be6c8c50f31ed96b00601-0000.us-east.containers.appdomain.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: bee-ui
              servicePort: 80
